#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HuiErPu")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertGarbage(Garbage instance);
  partial void UpdateGarbage(Garbage instance);
  partial void DeleteGarbage(Garbage instance);
  partial void Insertmanger(manger instance);
  partial void Updatemanger(manger instance);
  partial void Deletemanger(manger instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HuiErPuConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Garbage> Garbage
	{
		get
		{
			return this.GetTable<Garbage>();
		}
	}
	
	public System.Data.Linq.Table<manger> manger
	{
		get
		{
			return this.GetTable<manger>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Garbage")]
public partial class Garbage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Onum;
	
	private string _GN;
	
	private string _PO_;
	
	private string _SN;
	
	private System.Nullable<System.DateTime> _ST;
	
	private System.Nullable<System.DateTime> _RT;
	
	private string _OW;
	
	private System.Nullable<int> _Flag;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOnumChanging(string value);
    partial void OnOnumChanged();
    partial void OnGNChanging(string value);
    partial void OnGNChanged();
    partial void OnPO_Changing(string value);
    partial void OnPO_Changed();
    partial void OnSNChanging(string value);
    partial void OnSNChanged();
    partial void OnSTChanging(System.Nullable<System.DateTime> value);
    partial void OnSTChanged();
    partial void OnRTChanging(System.Nullable<System.DateTime> value);
    partial void OnRTChanged();
    partial void OnOWChanging(string value);
    partial void OnOWChanged();
    partial void OnFlagChanging(System.Nullable<int> value);
    partial void OnFlagChanged();
    #endregion
	
	public Garbage()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onum", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Onum
	{
		get
		{
			return this._Onum;
		}
		set
		{
			if ((this._Onum != value))
			{
				this.OnOnumChanging(value);
				this.SendPropertyChanging();
				this._Onum = value;
				this.SendPropertyChanged("Onum");
				this.OnOnumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GN", DbType="VarChar(30)")]
	public string GN
	{
		get
		{
			return this._GN;
		}
		set
		{
			if ((this._GN != value))
			{
				this.OnGNChanging(value);
				this.SendPropertyChanging();
				this._GN = value;
				this.SendPropertyChanged("GN");
				this.OnGNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PO#", Storage="_PO_", DbType="VarChar(30)")]
	public string PO_
	{
		get
		{
			return this._PO_;
		}
		set
		{
			if ((this._PO_ != value))
			{
				this.OnPO_Changing(value);
				this.SendPropertyChanging();
				this._PO_ = value;
				this.SendPropertyChanged("PO_");
				this.OnPO_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SN", DbType="VarChar(30)")]
	public string SN
	{
		get
		{
			return this._SN;
		}
		set
		{
			if ((this._SN != value))
			{
				this.OnSNChanging(value);
				this.SendPropertyChanging();
				this._SN = value;
				this.SendPropertyChanged("SN");
				this.OnSNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST", DbType="DateTime")]
	public System.Nullable<System.DateTime> ST
	{
		get
		{
			return this._ST;
		}
		set
		{
			if ((this._ST != value))
			{
				this.OnSTChanging(value);
				this.SendPropertyChanging();
				this._ST = value;
				this.SendPropertyChanged("ST");
				this.OnSTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RT", DbType="DateTime")]
	public System.Nullable<System.DateTime> RT
	{
		get
		{
			return this._RT;
		}
		set
		{
			if ((this._RT != value))
			{
				this.OnRTChanging(value);
				this.SendPropertyChanging();
				this._RT = value;
				this.SendPropertyChanged("RT");
				this.OnRTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OW", DbType="VarChar(30)")]
	public string OW
	{
		get
		{
			return this._OW;
		}
		set
		{
			if ((this._OW != value))
			{
				this.OnOWChanging(value);
				this.SendPropertyChanging();
				this._OW = value;
				this.SendPropertyChanged("OW");
				this.OnOWChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int")]
	public System.Nullable<int> Flag
	{
		get
		{
			return this._Flag;
		}
		set
		{
			if ((this._Flag != value))
			{
				this.OnFlagChanging(value);
				this.SendPropertyChanging();
				this._Flag = value;
				this.SendPropertyChanged("Flag");
				this.OnFlagChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.manger")]
public partial class manger : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _id;
	
	private string _pwd;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    #endregion
	
	public manger()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(10)")]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
